AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: cicd lambda phquerylogfile-dev
Resources:
  ATTFFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.8
      CodeUri: ./src
#      Layers:
#        - arn:aws-cn:lambda:cn-northwest-1:444603803904:layer:ph-schema-explorer:3
      FunctionName: phquerylogfile
      Description: "phquerylogfile-V2 "
      MemorySize: 512
      Role: arn:aws-cn:iam::444603803904:role/Ph-Back-RW
      Timeout: 30

