PH_NOTICE_IOT:
  metadata:
    name: PH_NOTICE_IOT
    bucket: ph-platform
    runtime: python3.8 # lambda funciton 会按照第一个使用， layer 全使用
    desc: 根据触发事件转发消息到 IOT
  layer:
    lib_path: .venv/lib/python3.8/site-packages
    package_name: PH_NOTICE_IOT-layer.zip
    layer_path: PH_NOTICE_IOT-layer.zip
    layer_desc: 根据触发事件转发消息到 IOT
  lambda:
    code_path: main.py
    package_name: PH_NOTICE_IOT-code.zip
    lambda_path: PH_NOTICE_IOT-code.zip
    lambda_handler: main.lambda_handler
    lambda_layers: PH_NOTICE_IOT
    lambda_desc: 根据触发事件转发消息到 IOT
    lambda_timeout: 30
    lambda_memory_size: 128
    # vpc_config:
    #   SubnetIds:
    #   - 'subnet-0260eab5acd58bc53'
    #   - 'subnet-0e3daa88acef9b136'
    #   SecurityGroupIds:
    #   - 'sg-058404c2ad02dcbb9'
    #   - 'sg-09f5205a1194149ab'
    lambda_env:
      TEST: test
    lambda_tag:
      language: python3.8
  gateway:
    rest_api_id: 2t69b7x032
    api_template: s3://ph-platform/2020-08-10/template/python/phcli/lmd/jsonapi-openapi-template.yaml
    lambda_name: PH_NOTICE_IOT
    alias_version: current
