AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: cicd lambda phmaxcompatible-V2
Resources:
  ATTFFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.8
      AutoPublishAlias: Current
      CodeUri: ./src
      FunctionName: lmd-phmaxcompatible-V2
      Description: "兼容max1。0"
      Role: arn:aws-cn:iam::444603803904:role/Ph-Back-RW
      MemorySize: 1024
      Timeout: 600
      Environment:
        Variables:
          EDITION: "V2"