project: "entry"
models:
  - file: SandboxIndex
    reg: sandbox-indices
  - file: FileVersion
    reg: file-versions
  - file: FileDetail
    reg: file-details
  - file: Asset
    reg: assets
  - file: DataSet
    reg: data-sets
  - file: Job
    reg: jobs
  - file: DbSource
    reg: db-sources
  - file: File
    reg: files
  - file: Mart
    reg: marts
mongo:
  algorithm: mongodb
  host: pharbers.com
  port: 5555
  username: ""
  pwd: ""
  coll: "pharbers-sandbox-merge"
  authSource: ""
  auth: false
env:
  oauthHost: oauth.pharbers.com
  oauthPort: ""
  oauthApiNamespace: "v0"
  kafkaBrokerList: "59.110.31.50:9092"
  kafkaTopic: "test"
  kafkaSecretsDir: "/Users/sunchenghao/secrets/"
  kafkaPassword: "pharbers"
  schemaRegisterHost: "59.110.31.50:8081"
  httpCallUrl: "http://59.110.31.50:28888/spark/job/run"
  httpCallRUrl: "http://59.110.31.50:9213/v1.0/job_reg"
oss:
  region: oss-cn-beijing
  accessKeyId: LTAI4Fuc5oo46peAcc3LmHb3
  accessKeySecret: aJRr3DP4nXCFDR3KGRICpIhq5bHfTm
  bucket: pharbers-PhSandBox
kfk:
  kafkaBrokerList: "http://broker-svc.message:8082"
  kafkaTopic: "alfredtest"
