AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: cicd lambda ph-notice-glue
Resources:
  ATTFFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.8
      AutoPublishAlias: Current
      CodeUri: ./src
      FunctionName: lmd-phcreatestepargs-V2
      Description: "生成Step在EMR上运行需要的参数"
      MemorySize: 128
      Role: arn:aws-cn:iam::444603803904:role/Ph-Cli-Lmd
      Timeout: 30
      Environment:
        Variables:
          EDITION: "DEV"
