AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: cicd lambda phgetgluetable
Resources:
  ATTFFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: phgetgluetable.lambda_handler
      Runtime: python3.8
      AutoPublishAlias: Current
      CodeUri: ./src
      #Layers:
      FunctionName: lmd-phgetgluetable-V2
      Description: "获取glue数据库table name"
      MemorySize: 512
      Role: arn:aws-cn:iam::444603803904:role/Pharbers-ETL-Roles
      Timeout: 120
      VpcConfig:
        SecurityGroupIds:
          - sg-058404c2ad02dcbb9
          - sg-09f5205a1194149ab
        SubnetIds:
          - subnet-0260eab5acd58bc53
          - subnet-0e3daa88acef9b136