
const fields = {
    year: Number,
    quarter: Number,
    month: Number,
    mkt: String,
    moleName: String,
    productName: String,
    countryName: String,
    provinceName: String,
    cityName: String,
    salesValue: Number,
    salesQty: Number,
    prodCurLevel: String,
    geoCurLevel: String,
    timeCurLevel: String,
    prodParpentValue: Number,
    geoParpentValue: Number,
    timeParpentValue: Number,
    prodPpValue: Number,
    lattles: String,
    marketShare: Number,
    moleShare: Number,
    prodMoleShare: Number,
    timeProviousValue: Number,
    timeProviousShareValue: Number,
    marketSalesGrowth: Number,
    salesGrowth: Number,
    ei: Number,
}

const records = {
    aohong: fields,
    astellas: fields,
    az: fields,
    beite: fields,
    gilead: fields,
    haikun: fields,
    huiyu: fields,
    jingxin: fields,
    kangzhe: fields,
    mylan: fields,
    nhwa: fields,
    pfizer: fields,
    qilu: fields,
    sankyo: fields,
    sanofi: fields,
    servier: fields,
    tide: fields,
    xlt: fields
}

export default records
