AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: cicd lambda
Resources:
  ATTFFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.8
      CodeUri: ./src
      FunctionName: phscenariosendemail
      MemorySize: 1024
      Description: "phscenariosendemail"
      Role: arn:aws-cn:iam::444603803904:role/Ph-Back-RW
      Layers:
        - arn:aws-cn:lambda:cn-northwest-1:444603803904:layer:phpandas:2
      Environment:
        Variables:
          EDITION: "DEV"
          SENDMAILBOX: "project@data-pharbers.com"
          SENDPW: "qiye@126"
          TOMAILBOX: "alfredyang@pharbers.com"
          SENDNICKNAME: "Pharbers Scenario"
          TONICKNAME: "Hello, strange."


