AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Deploy lmd phoffweb
Resources:
  ATTFFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      AutoPublishAlias: Current
      CodeUri: ./lmdcode
      FunctionName: phoffweb-v2
      Description: "官网"
      Timeout: 30
      Role: arn:aws-cn:iam::444603803904:role/Ph-Cli-Lmd
      MemorySize: 1024
      Layers:
        - arn:aws-cn:lambda:cn-northwest-1:444603803904:layer:base-layer-node:14
        - arn:aws-cn:lambda:cn-northwest-1:444603803904:layer:lbdauth:5
      Environment:
        Variables:
          TEST: test
          configs: '[{"name":"Postgres","entity":"offweb","database":"phoffweb","user":"pharbers","password":"Abcde196125","host":"192.168.49.199","port":5439,"poolMax":1}]'
      VpcConfig:
        SecurityGroupIds:
          - sg-058404c2ad02dcbb9
          - sg-09f5205a1194149ab
        SubnetIds:
          - subnet-0260eab5acd58bc53
          - subnet-0e3daa88acef9b136

