phproject:
  metadata:
    name: phproject
    bucket: ph-platform
    runtime: nodejs14.x # lambda funciton 会按照第一个使用， layer 全使用
    desc: Step Functions 展示
  layer:
    lib_path: node_modules
    package_name: phproject-layer.zip
    layer_path: phproject-layer.zip
    layer_desc: Step Functions 展示
  lambda:
    code_path: app.js,dist
    package_name: phproject-code.zip
    lambda_path: phproject-code.zip
    lambda_handler: app.lambdaHandler
    lambda_layers: phproject,base-layer-node,lbdauth
    lambda_desc: Step Functions 展示
    lambda_timeout: 30
    lambda_memory_size: 512
    vpc_config:
      SubnetIds:
      - 'subnet-0260eab5acd58bc53'
      - 'subnet-0e3daa88acef9b136'
      SecurityGroupIds:
      - 'sg-058404c2ad02dcbb9'
      - 'sg-09f5205a1194149ab'
    lambda_env:
      TEST: test
#      AccessKeyId: AKIAWPBDTVEAI6LUCLPX
#      SecretAccessKey: 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
    lambda_tag:
      language: nodejs14.x
  gateway:
    rest_api_id: 2t69b7x032
    api_template: s3://ph-platform/2020-08-10/template/python/phcli/lmd/jsonapi-openapi-template.yaml
    lambda_name: phproject
    alias_version: current
