AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: cicd lambda
Resources:
  ATTFFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.8
      CodeUri: ./src
      FunctionName: phresourcecodegengroupby
      Layers:
        - arn:aws-cn:lambda:cn-northwest-1:444603803904:layer:pyyaml:1
      MemorySize: 1024
      Description: "phresourcecodegengroupby"
      Role: arn:aws-cn:iam::444603803904:role/Ph-Back-RW
      Environment:
        Variables:
          EDITION: "release"
          BUCKET: ph-platform
          CLI_VERSION: 2020-11-11
          DAG_S3_JOBS_PATH: /jobs/python/phcli


