ph_start_ETL_step:
  metadata:
    name: ph_start_ETL_step
    bucket: ph-platform
    runtime: python3.8 # lambda funciton 会按照第一个使用， layer 全使用
    desc: 用来启动ETL的StepFunticon
  layer:
    lib_path: .venv/lib/python3.8/site-packages
    package_name: ph_start_ETL_step-layer.zip
    layer_path: ph_start_ETL_step-layer.zip
    layer_desc: 用来启动ETL的StepFunticon
  lambda:
    code_path: src
    package_name: ph_start_ETL_step-code.zip
    lambda_path: ph_start_ETL_step-code.zip
    lambda_handler: src.main.lambda_handler
    lambda_layers: ph_start_ETL_step
    lambda_desc: 用来启动ETL的StepFunticon
    lambda_timeout: 30
    lambda_memory_size: 128
#    vpc_config:
#      SubnetIds:
#      - 'subnet-0260eab5acd58bc53'
#      - 'subnet-0e3daa88acef9b136'
#      SecurityGroupIds:
#      - 'sg-058404c2ad02dcbb9'
#      - 'sg-09f5205a1194149ab'
    lambda_env:
      DEFAULT_ROLE_ARN: arn:aws-cn:iam::444603803904:role/Ph-Data-Resource-Admin
    lambda_tag:
      language: python3.8
  gateway:
    rest_api_id: 2t69b7x032
    api_template: s3://ph-platform/2020-08-10/template/python/phcli/lmd/jsonapi-openapi-template.yaml
    lambda_name: ph_start_ETL_step
    alias_version: current
