project: "components"
models:
  - file: Component
    reg: components
  - file: Datasource
    reg: datasources
mongo:
  algorithm: mongodb
  host: 123.56.179.133
  port: 5555
  username: alfredyang
  pwd: "12345"
  coll: "pharbers-components"
  authSource: "admin"
  auth: false
