AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: cicd lambda
Resources:
  ATTFFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.8
      AutoPublishAlias: Current
      CodeUri: ./src
      Layers:
        -
        - arn:aws-cn:lambda:cn-northwest-1:444603803904:layer:phdydatasource:1
        - arn:aws-cn:lambda:cn-northwest-1:444603803904:layer:redis:1
      FunctionName: lmd-phterminationargsvalidation-dev
      MemorySize: 1024
      Description: "phterminationargsvalidation"
      Role: arn:aws-cn:iam::444603803904:role/Ph-Back-RW
      Environment:
        Variables:
          EDITION: "DEV"


