version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - python3 -m pytest --junitxml=$PROJECT_NAME-report-directory/$PROJECT_NAME-report-file.xml
      - sam package --template-file template.yaml --output-template-file package.yaml --s3-bucket ph-platform --s3-prefix 2020-11-11/cicd/phresdeletiondsresource/samtem/v2
      - sam deploy --template-file package.yaml --stack-name lmd-phresdeletiondsresource-deploy-v2 --capabilities CAPABILITY_IAM
artifacts:
  files:
    - src/**/**
  type: zip
  name: $PROJECT_NAME-$(date +%Y-%m-%d)
  s3-prefix: 2020-11-11/cicd/$PROJECT_NAME/artifacts

reports:
  arn:aws-cn:codebuild:cn-northwest-1:444603803904:report-group/phlambda-project-phlambda-report-group:
    files:
      - $PROJECT_NAME-report-file.xml
    base-directory: $PROJECT_NAME-report-directory
    file-format: JUNITXML
