AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: cicd lambda
Resources:
  ATTFFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.8
      CodeUri: ./src
      Layers:
        - arn:aws-cn:lambda:cn-northwest-1:444603803904:layer:phdydatasource:1
      FunctionName: phcomputedeletionimpact
      MemorySize: 1024
      Description: "计算删除DS产生的影响"
      Role: arn:aws-cn:iam::444603803904:role/Ph-Back-RW
      Timeout: 30
      Tags:
        edition: release
        owner: pqian
        version: Beta
        api: v2

