AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: cicd lambda phrollback
Resources:
  ATTFFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: phrollback.lambda_handler
      Runtime: python3.8
      AutoPublishAlias: Current
      CodeUri: ./src
      #Layers:
      FunctionName: lmd-phrollback-V2
      Description: "数据回滚"
      MemorySize: 512
      Role: arn:aws-cn:iam::444603803904:role/Ph-Data-Resource-Admin
      Timeout: 120
      VpcConfig:
        SecurityGroupIds:
          - sg-058404c2ad02dcbb9
          - sg-09f5205a1194149ab
        SubnetIds:
          - subnet-0260eab5acd58bc53
          - subnet-0e3daa88acef9b136