AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: cicd lambda phdadataupdata-dev
Resources:
  ATTFFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.8
      CodeUri: ./src
#      Layers:
#        - arn:aws-cn:lambda:cn-northwest-1:444603803904:layer:ph-schema-explorer:3
      FunctionName: phdadataupdata
      Description: "phchdatasource-v2 "
      MemorySize: 512
      Role: arn:aws-cn:iam::444603803904:role/Ph-Cli-Lmd
      Timeout: 5
      Environment:
        Variables:
          HOST: "pharbers-cache.xtjxgq.0001.cnw1.cache.amazonaws.com.cn"
          PORT: "6379"
          APP_NAME: "phchdatasource"

