AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: cicd lambda
Resources:
  ATTFFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.8
      AutoPublishAlias: Current
      CodeUri: ./src
      Layers:
        - arn:aws-cn:lambda:cn-northwest-1:444603803904:layer:phdydatasource:1
        - arn:aws-cn:lambda:cn-northwest-1:444603803904:layer:redis:1
      FunctionName: lmd-phsyncdagconf-V2
      MemorySize: 1024
      Description: "创建dagconf 同时创建dag, airflow运行文件"
      Role: arn:aws-cn:iam::444603803904:role/Ph-Back-RW
      Environment:
        Variables:
          REDIS_HOST: "pharbers-cache.xtjxgq.0001.cnw1.cache.amazonaws.com.cn"
          REDIS_PORT: "6379"
          EDITION: "V2"
      Tags:
        edition: dev
        owner: hbzhao
        version: Alpha
        api: v1
#      Events:
#        DBactionEvent:
#          Type: DynamoDB
#          Properties:
#            Stream: arn:aws-cn:dynamodb:cn-northwest-1:444603803904:table/action/stream/2021-10-28T14:27:14.729
#            StartingPosition: TRIM_HORIZON
#            BatchSize: 1
#            Enabled: No
      FileSystemConfigs:
        - Arn: arn:aws-cn:elasticfilesystem:cn-northwest-1:444603803904:access-point/fsap-03c2a9f1b9fcf6942
          LocalMountPath: /mnt/tmp
      Timeout: 600
      VpcConfig:
        SecurityGroupIds:
          - sg-058404c2ad02dcbb9
          - sg-09f5205a1194149ab
        SubnetIds:
          - subnet-0260eab5acd58bc53
          - subnet-0e3daa88acef9b136


