AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: cicd lambda ph-notice-email
Resources:
  ATTFFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.8
      AutoPublishAlias: Current
      CodeUri: s3://ph-platform/2020-11-11/cicd/phprojectefs/samtem/ae7564574b993ca27262ca3cf7b017b0
      FunctionName: lmd-phprojectefs-dev
      Description: "\u6839\u636E\u89E6\u53D1\u4E8B\u4EF6 \u5BF9efs\u4E2Dproject\u7684\
        \u8D44\u6E90\u8FDB\u884C\u64CD\u4F5C"
      MemorySize: 128
      Role: arn:aws-cn:iam::444603803904:role/Ph-Data-Resource-Admin
      Timeout: 30
      VpcConfig:
        SecurityGroupIds:
        - sg-058404c2ad02dcbb9
        - sg-09f5205a1194149ab
        SubnetIds:
        - subnet-0260eab5acd58bc53
        - subnet-0e3daa88acef9b136
