AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Deploy lmd lmd-phcreateproject-V2
Resources:
  ATTFFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      AutoPublishAlias: Current
      CodeUri: ./lmdcode
      FunctionName: lmd-phcreateproject-V2
      Description: "创建Project，该接口可废弃，可直接调用platform"
      Timeout: 600
      Role: arn:aws-cn:iam::444603803904:role/Pharbers-ETL-Roles
      MemorySize: 1024
      Layers:
        - arn:aws-cn:lambda:cn-northwest-1:444603803904:layer:base-layer-node:14
        - arn:aws-cn:lambda:cn-northwest-1:444603803904:layer:lbdauth:5
        - arn:aws-cn:lambda:cn-northwest-1:444603803904:layer:phcreateproject:1
      FileSystemConfigs:
        - Arn: arn:aws-cn:elasticfilesystem:cn-northwest-1:444603803904:access-point/fsap-03c2a9f1b9fcf6942
          LocalMountPath: /mnt/tmp
      Environment:
        Variables:
          MOUNTPATH: /mnt/tmp/
          EDITION: "V2"
          ENTITY: "platform"
          DATABASE: "phplatform"
          USER: "pharbers"
          PASSWORD: "Abcde196125"
          HOST: "192.168.26.64"
          PORT: "5439"
      VpcConfig:
        SecurityGroupIds:
          - sg-058404c2ad02dcbb9
          - sg-09f5205a1194149ab
        SubnetIds:
          - subnet-0260eab5acd58bc53
          - subnet-0e3daa88acef9b136
