AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: lambda
Resources:
  ATTFFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.8
      AutoPublishAlias: Current
      CodeUri: ./src
      FunctionName: lmd-phlogscollection2db-dev
      MemorySize: 1024
      Environment:
        Variables:
          EDITION: "DEV"
      Description: "phlogscollection2db"
      Role: arn:aws-cn:iam::444603803904:role/Ph-Back-RW



