AWS_REGION = "cn-northwest-1"

ASSUME_ROLE_ARN = "YXJuOmF3cy1jbjppYW06OjQ0NDYwMzgwMzkwNDpyb2xlL1BoLUJhY2stUlc="

FILTER_COL_REG = "[\n\t\s（），+()-./\"'\\\\]"

BATCH_SIZE = "BATCH_SIZE"
CLICKHOUSE_HOST = "CLICKHOUSE_HOST"
CLICKHOUSE_PORT = "CLICKHOUSE_PORT"
CLICKHOUSE_DB = "CLICKHOUSE_DB"
REDIS_HOST = "REDIS_HOST"
REDIS_PORT = "REDIS_PORT"
LOCK_APP_NAME = "LOCK_APP_NAME"
CHECK_APP_NAME = "CHECK_APP_NAME"
FILE_PATH = "PATH_PREFIX"
DEV = "EDITION"

TYPE_STRUCTURE = {
    "String": str
}
