PH_WOWRFLOW:
  metadata:
    name: PH_WOWRFLOW
    bucket: ph-platform
    runtime: python3.8 # lambda funciton 会按照第一个使用， layer 全使用
    desc: step_functions使用
  layer:
    lib_path: .venv/lib/python3.8/site-packages
    package_name: PH_WOWRFLOW-layer.zip
    layer_path: PH_WOWRFLOW-layer.zip
    layer_desc: step_functions使用
  lambda:
    code_path: src
    package_name: PH_WOWRFLOW-code.zip
    lambda_path: PH_WOWRFLOW-code.zip
    lambda_handler: src.main.lambda_handler
    lambda_layers: PH_WOWRFLOW
    lambda_desc: step_functions使用
    lambda_timeout: 30
    lambda_memory_size: 128
    # vpc_config:
    #   SubnetIds:
    #   - 'subnet-0260eab5acd58bc53'
    #   - 'subnet-0e3daa88acef9b136'
    #   SecurityGroupIds:
    #   - 'sg-058404c2ad02dcbb9'
    #   - 'sg-09f5205a1194149ab'
    lambda_env:
      DEFAULT_ROLE_ARN: arn:aws-cn:iam::444603803904:role/Pharbers-IoC-Maintainer
    lambda_tag:
      language: python3.8
  gateway:
    rest_api_id: 2t69b7x032
    api_template: s3://ph-platform/2020-08-10/template/python/phcli/lmd/jsonapi-openapi-template.yaml
    lambda_name: PH_WOWRFLOW
    alias_version: current
