import datetime
'''
a = {'Partitions': [{'Values': ['common_202103'], 'DatabaseName': 'zudicg_17yj8ceuocthg', 'TableName': 'not_arrived',
                     'CreationTime': datetime.datetime(2022, 3, 24, 14, 9, 17, tzinfo=tzlocal()),
                     'LastAccessTime': datetime.datetime(2022, 3, 24, 14, 9, 17, tzinfo=tzlocal()),
                     'StorageDescriptor': {
                         'Columns': [{'Name': 'id', 'Type': 'string'}, {'Name': 'date', 'Type': 'string'},
                                     {'Name': 'owner', 'Type': 'string'}, {'Name': 'provider', 'Type': 'string'}],
                         'Location': 's3://ph-platform/2020-11-11/lake/pharbers/zudIcG_17yj8CEUoCTHg/not_arrived/version=common_202103/',
                         'InputFormat': 'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat',
                         'OutputFormat': 'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat',
                         'Compressed': False, 'NumberOfBuckets': -1, 'SerdeInfo': {
                             'SerializationLibrary': 'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe',
                             'Parameters': {'serialization.format': '1'}}, 'BucketColumns': [], 'SortColumns': [],
                         'Parameters': {'averageRecordSize': '14', 'classification': 'parquet',
                                        'compressionType': 'none', 'objectCount': '2', 'recordCount': '97',
                                        'sizeKey': '3036', 'typeOfData': 'file'}, 'StoredAsSubDirectories': False},
                     'Parameters': {}, 'CatalogId': '444603803904'},
                    {'Values': ['common_201812'], 'DatabaseName': 'zudicg_17yj8ceuocthg', 'TableName': 'not_arrived',
                     'CreationTime': datetime.datetime(2022, 3, 24, 14, 9, 17, tzinfo=tzlocal()),
                     'LastAccessTime': datetime.datetime(2022, 3, 24, 14, 9, 17, tzinfo=tzlocal()),
                     'StorageDescriptor': {
                         'Columns': [{'Name': 'id', 'Type': 'string'}, {'Name': 'date', 'Type': 'string'},
                                     {'Name': 'owner', 'Type': 'string'}, {'Name': 'provider', 'Type': 'string'}],
                         'Location': 's3://ph-platform/2020-11-11/lake/pharbers/zudIcG_17yj8CEUoCTHg/not_arrived/version=common_201812/',
                         'InputFormat': 'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat',
                         'OutputFormat': 'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat',
                         'Compressed': False, 'NumberOfBuckets': -1, 'SerdeInfo': {
                             'SerializationLibrary': 'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe',
                             'Parameters': {'serialization.format': '1'}}, 'BucketColumns': [], 'SortColumns': [],
                         'Parameters': {'averageRecordSize': '8', 'classification': 'parquet',
                                        'compressionType': 'none', 'objectCount': '2', 'recordCount': '223',
                                        'sizeKey': '3378', 'typeOfData': 'file'}, 'StoredAsSubDirectories': False},
                     'Parameters': {}, 'CatalogId': '444603803904'},
                    {'Values': ['common_202101'], 'DatabaseName': 'zudicg_17yj8ceuocthg', 'TableName': 'not_arrived',
                     'CreationTime': datetime.datetime(2022, 3, 24, 14, 9, 17, tzinfo=tzlocal()),
                     'LastAccessTime': datetime.datetime(2022, 3, 24, 14, 9, 17, tzinfo=tzlocal()),
                     'StorageDescriptor': {
                         'Columns': [{'Name': 'id', 'Type': 'string'}, {'Name': 'date', 'Type': 'string'},
                                     {'Name': 'owner', 'Type': 'string'}, {'Name': 'provider', 'Type': 'string'}],
                         'Location': 's3://ph-platform/2020-11-11/lake/pharbers/zudIcG_17yj8CEUoCTHg/not_arrived/version=common_202101/',
                         'InputFormat': 'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat',
                         'OutputFormat': 'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat',
                         'Compressed': False, 'NumberOfBuckets': -1, 'SerdeInfo': {
                             'SerializationLibrary': 'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe',
                             'Parameters': {'serialization.format': '1'}}, 'BucketColumns': [], 'SortColumns': [],
                         'Parameters': {'averageRecordSize': '25', 'classification': 'parquet',
                                        'compressionType': 'none', 'objectCount': '2', 'recordCount': '40',
                                        'sizeKey': '2697', 'typeOfData': 'file'}, 'StoredAsSubDirectories': False},
                     'Parameters': {}, 'CatalogId': '444603803904'},
                    {'Values': ['common_202102'], 'DatabaseName': 'zudicg_17yj8ceuocthg', 'TableName': 'not_arrived',
                     'CreationTime': datetime.datetime(2022, 3, 24, 14, 9, 17, tzinfo=tzlocal()),
                     'LastAccessTime': datetime.datetime(2022, 3, 24, 14, 9, 17, tzinfo=tzlocal()),
                     'StorageDescriptor': {
                         'Columns': [{'Name': 'id', 'Type': 'string'}, {'Name': 'date', 'Type': 'string'},
                                     {'Name': 'owner', 'Type': 'string'}, {'Name': 'provider', 'Type': 'string'}],
                         'Location': 's3://ph-platform/2020-11-11/lake/pharbers/zudIcG_17yj8CEUoCTHg/not_arrived/version=common_202102/',
                         'InputFormat': 'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat',
                         'OutputFormat': 'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat',
                         'Compressed': False, 'NumberOfBuckets': -1, 'SerdeInfo': {
                             'SerializationLibrary': 'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe',
                             'Parameters': {'serialization.format': '1'}}, 'BucketColumns': [], 'SortColumns': [],
                         'Parameters': {'averageRecordSize': '17', 'classification': 'parquet',
                                        'compressionType': 'none', 'objectCount': '2', 'recordCount': '76',
                                        'sizeKey': '2940', 'typeOfData': 'file'}, 'StoredAsSubDirectories': False},
                     'Parameters': {}, 'CatalogId': '444603803904'},
                    {'Values': ['common_202012'], 'DatabaseName': 'zudicg_17yj8ceuocthg', 'TableName': 'not_arrived',
                     'CreationTime': datetime.datetime(2022, 3, 24, 14, 9, 17, tzinfo=tzlocal()),
                     'LastAccessTime': datetime.datetime(2022, 3, 24, 14, 9, 17, tzinfo=tzlocal()),
                     'StorageDescriptor': {
                         'Columns': [{'Name': 'id', 'Type': 'string'}, {'Name': 'date', 'Type': 'string'},
                                     {'Name': 'owner', 'Type': 'string'}, {'Name': 'provider', 'Type': 'string'}],
                         'Location': 's3://ph-platform/2020-11-11/lake/pharbers/zudIcG_17yj8CEUoCTHg/not_arrived/version=common_202012/',
                         'InputFormat': 'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat',
                         'OutputFormat': 'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat',
                         'Compressed': False, 'NumberOfBuckets': -1, 'SerdeInfo': {
                             'SerializationLibrary': 'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe',
                             'Parameters': {'serialization.format': '1'}}, 'BucketColumns': [], 'SortColumns': [],
                         'Parameters': {'averageRecordSize': '6', 'classification': 'parquet',
                                        'compressionType': 'none', 'objectCount': '2', 'recordCount': '491',
                                        'sizeKey': '4326', 'typeOfData': 'file'}, 'StoredAsSubDirectories': False},
                     'Parameters': {}, 'CatalogId': '444603803904'},
                    {'Values': ['common_202104'], 'DatabaseName': 'zudicg_17yj8ceuocthg', 'TableName': 'not_arrived',
                     'CreationTime': datetime.datetime(2022, 3, 24, 14, 9, 17, tzinfo=tzlocal()),
                     'LastAccessTime': datetime.datetime(2022, 3, 24, 14, 9, 17, tzinfo=tzlocal()),
                     'StorageDescriptor': {
                         'Columns': [{'Name': 'id', 'Type': 'string'}, {'Name': 'date', 'Type': 'string'},
                                     {'Name': 'owner', 'Type': 'string'}, {'Name': 'provider', 'Type': 'string'}],
                         'Location': 's3://ph-platform/2020-11-11/lake/pharbers/zudIcG_17yj8CEUoCTHg/not_arrived/version=common_202104/',
                         'InputFormat': 'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat',
                         'OutputFormat': 'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat',
                         'Compressed': False, 'NumberOfBuckets': -1, 'SerdeInfo': {
                             'SerializationLibrary': 'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe',
                             'Parameters': {'serialization.format': '1'}}, 'BucketColumns': [], 'SortColumns': [],
                         'Parameters': {'averageRecordSize': '12', 'classification': 'parquet',
                                        'compressionType': 'none', 'objectCount': '2', 'recordCount': '141',
                                        'sizeKey': '3234', 'typeOfData': 'file'}, 'StoredAsSubDirectories': False},
                     'Parameters': {}, 'CatalogId': '444603803904'},
                    {'Values': ['common_201912'], 'DatabaseName': 'zudicg_17yj8ceuocthg', 'TableName': 'not_arrived',
                     'CreationTime': datetime.datetime(2022, 3, 24, 14, 9, 17, tzinfo=tzlocal()),
                     'LastAccessTime': datetime.datetime(2022, 3, 24, 14, 9, 17, tzinfo=tzlocal()),
                     'StorageDescriptor': {
                         'Columns': [{'Name': 'id', 'Type': 'string'}, {'Name': 'date', 'Type': 'string'},
                                     {'Name': 'owner', 'Type': 'string'}, {'Name': 'provider', 'Type': 'string'}],
                         'Location': 's3://ph-platform/2020-11-11/lake/pharbers/zudIcG_17yj8CEUoCTHg/not_arrived/version=common_201912/',
                         'InputFormat': 'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat',
                         'OutputFormat': 'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat',
                         'Compressed': False, 'NumberOfBuckets': -1, 'SerdeInfo': {
                             'SerializationLibrary': 'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe',
                             'Parameters': {'serialization.format': '1'}}, 'BucketColumns': [], 'SortColumns': [],
                         'Parameters': {'averageRecordSize': '7', 'classification': 'parquet',
                                        'compressionType': 'none', 'objectCount': '2', 'recordCount': '348',
                                        'sizeKey': '3937', 'typeOfData': 'file'}, 'StoredAsSubDirectories': False},
                     'Parameters': {}, 'CatalogId': '444603803904'}],
     'NextToken': 'eyJsYXN0RXZhbHVhdGVkS2V5Ijp7IkhBU0hfS0VZIjp7InMiOiJwLmQ5YjQ4MWNlN2Y3NzRlNzZhY2NjMmU3OTZhYmVjYWNkLjg5In0sIlJBTkdFX0tFWSI6eyJzIjoiY29tbW9uXzIwMTkxMiJ9fSwiZXhwaXJhdGlvbiI6eyJzZWNvbmRzIjoxNjQ5ODI5MzQ5LCJuYW5vcyI6MzcxMDAwMDAwfSwicGFnZVNpemUiOjQ5NH0=',
     'ResponseMetadata': {'RequestId': '67669eb9-db25-4efa-98c6-f0d37ef41934', 'HTTPStatusCode': 200,
                          'HTTPHeaders': {'date': 'Tue, 12 Apr 2022 05:55:49 GMT',
                                          'content-type': 'application/x-amz-json-1.1', 'content-length': '7584',
                                          'connection': 'keep-alive',
                                          'x-amzn-requestid': '67669eb9-db25-4efa-98c6-f0d37ef41934'},
                          'RetryAttempts': 0}}

b = {'Partitions': [
    {'Values': ['pchc_city_tier'], 'DatabaseName': 'zudicg_17yj8ceuocthg', 'TableName': 'pchc_city_tier',
     'CreationTime': datetime.datetime(2022, 3, 9, 11, 7, 39, tzinfo=tzlocal()),
     'LastAccessTime': datetime.datetime(2022, 3, 9, 11, 7, 39, tzinfo=tzlocal()), 'StorageDescriptor': {
        'Columns': [{'Name': 'pchc', 'Type': 'string'}, {'Name': 'city', 'Type': 'string'},
                    {'Name': 'district', 'Type': 'string'}, {'Name': 'city_tier', 'Type': 'string'}],
        'Location': 's3://ph-platform/2020-11-11/lake/pharbers/zudIcG_17yj8CEUoCTHg/pchc_city_tier/version=pchc_city_tier/',
        'InputFormat': 'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat',
        'OutputFormat': 'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat', 'Compressed': False,
        'NumberOfBuckets': -1,
        'SerdeInfo': {'SerializationLibrary': 'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe',
                      'Parameters': {'serialization.format': '1'}}, 'BucketColumns': [], 'SortColumns': [],
        'Parameters': {'averageRecordSize': '16', 'classification': 'parquet', 'compressionType': 'none',
                       'objectCount': '1', 'recordCount': '10650', 'sizeKey': '80430', 'typeOfData': 'file'},
        'StoredAsSubDirectories': False}, 'Parameters': {}, 'CatalogId': '444603803904'}],
     'NextToken': 'eyJsYXN0RXZhbHVhdGVkS2V5Ijp7IkhBU0hfS0VZIjp7InMiOiJwLmQzZjU0MTFiZWQyMTQxNzY5OTA4MmQ1NTk3ZjRhMjRlLjExIn0sIlJBTkdFX0tFWSI6eyJzIjoicGNoY19jaXR5X3RpZXIifX0sImV4cGlyYXRpb24iOnsic2Vjb25kcyI6MTY0OTgzMzQ1MywibmFub3MiOjM5OTAwMDAwMH0sInBhZ2VTaXplIjo1MDB9',
     'ResponseMetadata': {'RequestId': 'bb4a6f8a-7f1f-4a59-8cd0-ddf3c6b2db3c', 'HTTPStatusCode': 200,
                          'HTTPHeaders': {'date': 'Tue, 12 Apr 2022 07:04:13 GMT',
                                          'content-type': 'application/x-amz-json-1.1', 'content-length': '1337',
                                          'connection': 'keep-alive',
                                          'x-amzn-requestid': 'bb4a6f8a-7f1f-4a59-8cd0-ddf3c6b2db3c'},
                          'RetryAttempts': 0}}

'''
c = 's3://ph-platform/2020-11-11/lake/pharbers/zudIcG_17yj8CEUoCTHg/not_arrived/version=common_202012/'

import re

a = [{'bt_pha': ['BT_PHA_20220331']}, {
    'chemdata': ['chemdata_data_ch_version_20210709_am_v1', 'chemdata_0707pm_20210707_pm_v1', 'chemdata_20210707_v1']},
     {'cn_corp_ref': ['cn_corp_ref_201912_1']}]
