AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: cicd lambda phclickhousesql
Resources:
  ATTFFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.8
      AutoPublishAlias: Current
      CodeUri: ./src
#      Layers:
#        - arn:aws-cn:lambda:cn-northwest-1:444603803904:layer:clickhouse_driver:1
      FunctionName: lmd-phchupdatesql-V2
      Description: "http proxy call chproxy execution to clickhouse"
      MemorySize: 512
      Role: arn:aws-cn:iam::444603803904:role/Ph-Cli-Lmd
      Environment:
        Variables:
          HOST: "pharbers-cache.xtjxgq.0001.cnw1.cache.amazonaws.com.cn"
          PORT: "6379"
          APP_NAME: "phchdatasource"
          EDITION: "DEV"
      Timeout: 30
      VpcConfig:
        SecurityGroupIds:
          - sg-058404c2ad02dcbb9
          - sg-09f5205a1194149ab
        SubnetIds:
          - subnet-0260eab5acd58bc53
          - subnet-0e3daa88acef9b136

