phcatlog:
  metadata:
    name: phcatlog
    bucket: ph-platform
    runtime: nodejs10.x # lambda funciton 会按照第一个使用， layer 全使用
    desc: 数据目录查询
  layer:
    lib_path: node_modules
    package_name: phcatlog-layer.zip
    layer_path: phcatlog-layer.zip
    layer_desc: 数据目录查询
  lambda:
    code_path: dist,app.js
    package_name: phcatlog-code.zip
    lambda_path: phcatlog-code.zip
    lambda_handler: app.lambdaHandler
    lambda_layers: phcatlog,base-layer-node,lbdauth
    lambda_desc: 数据目录查询
    lambda_timeout: 30
    lambda_memory_size: 128
#    vpc_config:
#      SubnetIds:
#      - 'subnet-0260eab5acd58bc53'
#      - 'subnet-0e3daa88acef9b136'
#      SecurityGroupIds:
#      - 'sg-058404c2ad02dcbb9'
#      - 'sg-09f5205a1194149ab'
    lambda_env:
      TEST: test
    lambda_tag:
      language: nodejs10.x
  gateway:
    rest_api_id: 2t69b7x032
    api_template: s3://ph-platform/2020-08-10/template/python/phcli/lmd/jsonapi-openapi-template.yaml
    lambda_name: phcatlog
    alias_version: current
