AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: cicd lambda ph-notice-email
Resources:
  ATTFFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.8
      AutoPublishAlias: Current
      CodeUri: ./src
      FunctionName: lmd-phresourceaction-V2
      Description: "通过传递的消息 对resource进行操作"
      MemorySize: 128
      Role: arn:aws-cn:iam::444603803904:role/Ph-Auto-Resource
      Timeout: 180
      Environment:
        Variables:
          EDITION: "DEV"

