AWS_REGION = "cn-northwest-1"

ASSUME_ROLE_ARN = "YXJuOmF3cy1jbjppYW06OjQ0NDYwMzgwMzkwNDpyb2xlL1BoLUJhY2stUlc="

FILTER_COL_REG = "[\n\t\s（），+()-./\"'\\\\]"

BATCH_SIZE = "BATCH_SIZE"
CLICKHOUSE_HOST = "CLICKHOUSE_HOST"
CLICKHOUSE_PORT = "CLICKHOUSE_PORT"
CLICKHOUSE_DB = "CLICKHOUSE_DB"
FILE_PATH = "PATH_PREFIX"
TYPE_STRUCTURE = {
    "String": str
}
