AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Deploy lmd lmd-phplatform-V2
Resources:
  ATTFFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      CodeUri: ./lmdcode
      FunctionName: phplatform
      Description: "JSONAPI Lambda cloudformation"
      Timeout: 600
      Role: arn:aws-cn:iam::444603803904:role/Pharbers-ETL-Roles
      MemorySize: 1024
      Layers:
        - arn:aws-cn:lambda:cn-northwest-1:444603803904:layer:base-layer-node:14
        - arn:aws-cn:lambda:cn-northwest-1:444603803904:layer:lbdauth:5
        - arn:aws-cn:lambda:cn-northwest-1:444603803904:layer:phplatform:2
      Environment:
        Variables:
          ACCESSKEYID: AKIAWPBDTVEAI6LUCLPX
          EDITION: "V2"
          ENTITY: "platform"
          DATABASE: "phplatform"
          USER: "pharbers"
          PASSWORD: "Abcde196125"
          HOST: "192.168.26.64"
          PORT: "5439"
      VpcConfig:
        SecurityGroupIds:
          - sg-058404c2ad02dcbb9
          - sg-09f5205a1194149ab
        SubnetIds:
          - subnet-0260eab5acd58bc53
          - subnet-0e3daa88acef9b136
