AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: cicd lambda
Resources:
  ATTFFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.8
      CodeUri: ./src
      Environment:
        Variables:
          EDITION: "release"
      FunctionName: actions
      Description: "对DynamoDB Action操作"
      Role: arn:aws-cn:iam::444603803904:role/Ph-Back-RW
      MemorySize: 1024
      Timeout: 600
      Tags:
        edition: release
        owner: pqian
        version: release
        api: v2
