AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: cicd lambda utilsnotification-DEV
Resources:
  ATTFFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.8
      AutoPublishAlias: Current
      CodeUri: ./src
      Environment:
        Variables:
          EDITION: "DEV"
      FunctionName: ph-utilsnotification-dev
      Description: "处理Action参数并写入DynamoDB，只做Action表的记录"
      Role: arn:aws-cn:iam::444603803904:role/Ph-Data-Resource-Admin
      MemorySize: 1024
      Timeout: 600
