AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: cicd lambda phetlsfn
Resources:
  ATTFFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.8
      AutoPublishAlias: Current
      CodeUri: s3://ph-platform/2020-11-11/cicd/phuploadwebfile/samtem/cbcb604d999d972377799575df33d622
      Layers:
      - arn:aws-cn:lambda:cn-northwest-1:444603803904:layer:lambda-git:3
      FunctionName: lmd-phuploadwebfile-V2
      Description: "\u63A5\u6536s3events \u5F53offweb artifacts \u4E0A\u4F20\u65F6\
        \u4E0B\u8F7Dartifact\u5206\u522B\u4E0A\u4F20file\u5230\u6307\u5B9A\u4F4D\u7F6E"
      Role: arn:aws-cn:iam::444603803904:role/Ph-Data-Resource-Admin
      Timeout: 60
      MemorySize: 1024
