version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      - python3 -m pytest --junitxml=phnoticeglue-report-directory/phnoticeglue-report-file.xml
      - sam package --template-file template.yaml --output-template-file /codebuild/output/package.yaml --s3-bucket ph-platform --s3-prefix 2020-11-11/cicd/phnoticeglue/samtem
      - sam deploy --template-file /codebuild/output/package.yaml --stack-name lmd-phnoticeglue-deploy --capabilities CAPABILITY_IAM
artifacts:
  files:
    - src/**/**
  type: zip
  name: phnoticeglue-$(date +%Y-%m-%d)
  s3-prefix: 2020-11-11/cicd/phnoticeglue/artifacts

reports:
  arn:aws-cn:codebuild:cn-northwest-1:444603803904:report-group/phlambda-project-phlambda-report-group:
    files:
      - phnoticeglue-report-file.xml
    base-directory: phnoticeglue-report-directory
    file-format: JUNITXML
