AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: cicd lambda
Resources:
  ATTFFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.8
      AutoPublishAlias: Current
      CodeUri: ./src
      FunctionName: lmd-phresourcecodegenpivot-dev
      Layers:
        - arn:aws-cn:lambda:cn-northwest-1:444603803904:layer:pyyaml:1
      MemorySize: 1024
      Description: "phresourcecodegenpivot"
      Role: arn:aws-cn:iam::444603803904:role/Ph-Back-RW
      Environment:
        Variables:
          EDITION: "V2"


