version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - mkdir -p /frontend-code/$COMPONENT_NAME/$REPO_NAME
      - cd /frontend-code/$COMPONENT_NAME/$REPO_NAME
      - git init
      - git pull $GIT_URL $BRANCH_NAME:$BRANCH_NAME
      - git checkout $GIT_COMMIT
      - cd vue-web-components/vue-basic-component
      - cp -r /node_modules/ .
      - yarn link
      - cd /frontend-code/$COMPONENT_NAME/$REPO_NAME/vue-web-components/vue-excelv2-component
      - cp -r /node_modules/ /frontend-code/$COMPONENT_NAME/$REPO_NAME/vue-web-components/vue-excelv2-component
      - cd /frontend-code/$COMPONENT_NAME/$REPO_NAME/$COMPONENT_PATH
      - cp -r /node_modules/ .
      - yarn link vue-components
      - npm run build:component || (echo 'run build error')
      - npm run build:component || (echo 'run build error')
      - npm run build:component
  build:
    commands:
      - ls
      - ls dist
      - echo `date +"%Y_%m_%d_%H_%M_%S"` >> dist/README.md
      - echo $GIT_COMMIT >> dist/README.md
      - cp .devops dist
      - aws s3 cp dist $S3_COMPONENT_PATH --recursive