project: "common"
postgres:
  algorithm: postgres
  host: localhost
  port: 5432
  username: "postgres"
  pwd: "196125"
  dbName: "phcommon"
mongo:
  algorithm: mongodb+srv
  host: ph-db-gp.wqegl.azure.mongodb.net
  port: 27017
  username: "pharbers"
  pwd: "Pharbers.84244216"
  coll: "pharbers-offweb-test"
  authSource: "admin"
  auth: true
