AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Deploy lmd ph-accounts
Resources:
  ATTFFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      CodeUri: ./lmdcode
      FunctionName: phaccounts
      Description: "phact负责用户的注册与忘记密码流程"
      Timeout: 30
      Role: arn:aws-cn:iam::444603803904:role/Ph-Cli-Lmd
      MemorySize: 1024
      Layers:
        - arn:aws-cn:lambda:cn-northwest-1:444603803904:layer:phact:4
        - arn:aws-cn:lambda:cn-northwest-1:444603803904:layer:base-layer-node:14
        - arn:aws-cn:lambda:cn-northwest-1:444603803904:layer:lbdauth:5
      Environment:
        Variables:
          EDITION: "V2"
          ENTITY: "common"
          DATABASE: "phplatform"
          USER: "pharbers"
          PASSWORD: "Abcde196125"
          HOST: "192.168.26.64"
          PORT: "5439"
      VpcConfig:
        SecurityGroupIds:
          - sg-058404c2ad02dcbb9
          - sg-09f5205a1194149ab
        SubnetIds:
          - subnet-0260eab5acd58bc53
          - subnet-0e3daa88acef9b136
