project: "entry"
postgres:
  algorithm: postgres
  host: 127.0.0.1
  port: 5432
  username: "postgres"
  pwd: "faiz"
  dbName: "phentry"
  poolMax: 1
  idleTimeoutMillis: 1000
  connectionTimeoutMillis: 1000
redis:
  dao: token
  algorithm: redis
  #host: pharbers-cache.xtjxgq.0001.cnw1.cache.amazonaws.com.cn
  host: 127.0.0.1
  port: 6379
  dbName: "0"
  poolMax: 1
  idleTimeoutMillis: 1000
  connectionTimeoutMillis: 1000