AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: cicd lambda ph-schema-explorer-v2
Resources:
  ATTFFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.8
      AutoPublishAlias: Current
      CodeUri: ./src
#      Layers:
#        - arn:aws-cn:lambda:cn-northwest-1:444603803904:layer:ph-schema-explorer:3
      FunctionName: lmd-phschemaexplorer-v2
      Description: "http proxy call chproxy execution to clickhouse "
      MemorySize: 512
      Role: arn:aws-cn:iam::444603803904:role/Ph-Cli-Lmd
      Environment:
        Variables:
          PATH_PREFIX: /mnt/tmp/
      Timeout: 30
      VpcConfig:
        SecurityGroupIds:
          - sg-058404c2ad02dcbb9
          - sg-09f5205a1194149ab
        SubnetIds:
          - subnet-0260eab5acd58bc53
          - subnet-0e3daa88acef9b136
