AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: cicd lambda phsampleerror
Resources:
  ATTFFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.8
      CodeUri: ./src
      FunctionName: phsampleerror
      Description: "phsampleerror"
      Role: arn:aws-cn:iam::444603803904:role/Ph-Data-Resource-Admin
      MemorySize: 1024
      Timeout: 600
      Layers:
        - arn:aws-cn:lambda:cn-northwest-1:444603803904:layer:PHErrorLayer:3
