AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: cicd lambda phphxlsxtockhouse-V2
Resources:
  ATTFFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.8
      AutoPublishAlias: Current
      CodeUri: ./src
      Environment:
        Variables:
          EDITION: "DEV"
          SPARK_DRIVER_MEMORY
          SPARK_DRIVER_CORES
          SPARK_DRIVER_EXTRAJAVAOPTIONS
          SPARK_EXECUTOR_CORES
          SPARK_EXECUTOR_MEMORY
          SPARK_EXECUTOR_EXTRAJAVAOPTIONS

      FunctionName: lmd-phstatemachinegen-dev
      Description: "batch 读取Excel数据，通过Http接口批量写入ClickHouse"
      Role: arn:aws-cn:iam::444603803904:role/Ph-Data-Resource-Admin
      MemorySize: 1024
      Timeout: 600
      VpcConfig:
        SecurityGroupIds:
          - sg-058404c2ad02dcbb9
          - sg-09f5205a1194149ab
        SubnetIds:
          - subnet-0260eab5acd58bc53
          - subnet-0e3daa88acef9b136
