AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Deploy lmd phsfnIterator-v2
Resources:
  ATTFFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs14.x
      AutoPublishAlias: Current
      CodeUri: ./lmdcode
      FunctionName: lmd-phsfnIterator-V2
      Description: "ETL流程中迭代器"
      MemorySize: 1024
      Environment:
        Variables:
          EDITION: "DEV"
      Timeout: 30
      Role: arn:aws-cn:iam::444603803904:role/Ph-Cli-lmd
