phpowerbi:
  metadata:
    name: phpowerbi
    bucket: ph-platform
    runtime: nodejs14.x # lambda funciton 会按照第一个使用， layer 全使用
    desc: Power BI获取Token
  layer:
    lib_path: node_modules
    package_name: phpowerbi-layer.zip
    layer_path: phpowerbi-layer.zip
    layer_desc: Power BI获取Token
  lambda:
    code_path: dist,app.js
    package_name: phpowerbi-code.zip
    lambda_path: phpowerbi-code.zip
    lambda_handler: app.lambdaHandler
    lambda_layers: phpowerbi
    lambda_desc: Power BI获取Token
    lambda_timeout: 30
    lambda_memory_size: 512
    vpc_config:
      SubnetIds:
      - 'subnet-0260eab5acd58bc53'
      - 'subnet-0e3daa88acef9b136'
      SecurityGroupIds:
      - 'sg-058404c2ad02dcbb9'
      - 'sg-09f5205a1194149ab'
    lambda_env:
      CLIENTID: d05ed8c1-bb5d-4534-a7aa-1ffca7696a87
      CLIENTSECRET: K0XsmQv.NX45~Zc1gU.19OWicrzE0BC~hU
      EMBEDDEDURI: https://api.powerbi.cn/v1.0/myorg/groups/{gid}/reports/{rid}/GenerateToken
      PARTNERID: 2a606eef-e7e9-41a4-8b05-9e1a4942d602
      POWERBIURI: https://login.chinacloudapi.cn/{partnerId}/oauth2/token
      RESOURCE: https://analysis.chinacloudapi.cn/powerbi/api
    lambda_tag:
      language: nodejs14.x
  gateway:
    rest_api_id: 2t69b7x032
    api_template: s3://ph-platform/2020-08-10/template/python/phcli/lmd/jsonapi-openapi-template.yaml
    lambda_name: phpowerbi
    alias_version: current
