AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Deploy lmd phoauth
Resources:
  ATTFFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      AutoPublishAlias: Current
      CodeUri: ./lmdcode
      FunctionName: phoauth-v2
      Description: "oauth核心逻辑 cloudformation"
      Timeout: 30
      Role: arn:aws-cn:iam::444603803904:role/Ph-Cli-Lmd
      MemorySize: 1024
        Layers:
          - arn:aws-cn:lambda:cn-northwest-1:444603803904:layer:phact:3
      Environment:
        Variables:
          TEST: test
          configs: '[ { "name": "Postgres", "entity": "db/oauth", "database": "phcommon", "user": "pharbers", "password": "Abcde196125", "host": "192.168.49.199", "port": 5441, "poolMax": 1, "ssl": false, "idleTimeoutMs": 30000, "connectionTimeoutMs": 30000 }, { "name": "Redis", "entity": "db/token", "database": "0", "user": "", "password": "", "host": "pharbers-cache.xtjxgq.0001.cnw1.cache.amazonaws.com.cn", "port": 6379, "poolMax": 1 } ]'
      VpcConfig:
        SecurityGroupIds:
          - sg-058404c2ad02dcbb9
          - sg-09f5205a1194149ab
        SubnetIds:
          - subnet-0260eab5acd58bc53
          - subnet-0e3daa88acef9b136
