AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Deploy lmd ph-catlog
Resources:
  ATTFFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      AutoPublishAlias: Current
      CodeUri: ./lmdcode
      FunctionName: lmd-phapplyuser-V2
      Description: ""
      Timeout: 30
      Role: arn:aws-cn:iam::444603803904:role/offweb-lambda-role
      MemorySize: 128
      Layers:
        - arn:aws-cn:lambda:cn-northwest-1:444603803904:layer:offweb:4
      VpcConfig:
        SecurityGroupIds:
          - sg-058404c2ad02dcbb9
          - sg-09f5205a1194149ab
        SubnetIds:
          - subnet-0260eab5acd58bc53
          - subnet-0e3daa88acef9b136
