AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: cicd lambda
Resources:
  ATTFFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.8
      AutoPublishAlias: Current
      CodeUri: ./src
      FunctionName: lmd-phtriggersresources-dev
      MemorySize: 1024
      Description: "phtriggersresources"
      Role: arn:aws-cn:iam::444603803904:role/Ph-Back-RW
      Environment:
        Variables:
          EDITION: "DEV"
          TARGETARN: "arn:aws-cn:lambda:cn-northwest-1:444603803904:function:lmd-phscenariotriggerhandler-dev"
          TEMPLATEURL: "https://ph-platform.s3.cn-northwest-1.amazonaws.com.cn/2020-11-11/jobs/statemachine/pharbers/template/scenario-timer-cfn.yaml"

