AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Deploy lmd phproject-v2
Resources:
  ATTFFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      AutoPublishAlias: Current
      CodeUri: ./lmdcode
      FunctionName: lmd-phs3explorer-V2
      Description: "异步调用函数处理S3 Tags"
      MemorySize: 1024
      Layers:
        - arn:aws-cn:lambda:cn-northwest-1:444603803904:layer:phs3explorer:1
        - arn:aws-cn:lambda:cn-northwest-1:444603803904:layer:base-layer-node:14
        - arn:aws-cn:lambda:cn-northwest-1:444603803904:layer:lbdauth:5
      Timeout: 30
      Role: arn:aws-cn:iam::444603803904:role/Pharbers-ETL-Roles
      Environment:
        Variables:
          PATH_PREFIX: /mnt/tmp/
          EDITION: "DEV"
      VpcConfig:
        SecurityGroupIds:
          - sg-058404c2ad02dcbb9
          - sg-09f5205a1194149ab
        SubnetIds:
          - subnet-0260eab5acd58bc53
          - subnet-0e3daa88acef9b136

