PhCICD:
  metadata:
    name: PhCICD
    bucket: ph-platform
    runtime: python3.8 # lambda funciton 会按照第一个使用， layer 全使用
    desc: PhCICD
  layer:
    lib_path: .venv/lib/python3.8/site-packages
    package_name: PhCICD-layer.zip
    layer_path: PhCICD-layer.zip
    layer_desc: PhCICD
  lambda:
    code_path: src
    package_name: PhCICD-code.zip
    lambda_path: PhCICD-code.zip
    lambda_handler: src.main.lambda_handler
    lambda_layers: PhCICD
    lambda_desc: PhCICD
    lambda_timeout: 30
    lambda_memory_size: 128
    # vpc_config:
    #   SubnetIds:
    #   - 'subnet-0260eab5acd58bc53'
    #   - 'subnet-0e3daa88acef9b136'
    #   SecurityGroupIds:
    #   - 'sg-058404c2ad02dcbb9'
    #   - 'sg-09f5205a1194149ab'
    lambda_env:
      TEST: test
    lambda_tag:
      language: python3.8
  gateway:
    rest_api_id: 2t69b7x032
    api_template: s3://ph-platform/2020-08-10/template/python/phcli/lmd/jsonapi-openapi-template.yaml
    lambda_name: PhCICD
    alias_version: current
