AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: cicd lambda phclickhousesql
Resources:
  ATTFFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.8
      AutoPublishAlias: Current
      CodeUri: ./src
      Layers:
        - arn:aws-cn:lambda:cn-northwest-1:444603803904:layer:clickhouse_driver:1
      FunctionName: lmd-phclickhousesql-V2
      Description: "读取 glue 获得 scheme , 生成clickhouse table 的sql, 运行sql创建Table "
      Role: arn:aws-cn:iam::444603803904:role/Ph-Data-Resource-Admin
      Timeout: 120
