ph-schedule:
  metadata:
    name: ph-schedule
    bucket: ph-platform
    runtime: nodejs10.x # lambda funciton 会按照第一个使用， layer 全使用
    desc: 刘处流处理调度与postgresql数据交互
  layer:
    lib_path: node_modules
    package_name: ph-schedule-layer.zip
    layer_path: ph-schedule-layer.zip
    layer_desc: 刘处流处理调度与postgresql数据交互
  lambda:
    code_path: config,lib,dist,app.js
    package_name: ph-schedule-code.zip
    lambda_path: ph-schedule-code.zip
    lambda_handler: app.lambdaHandler
    lambda_layers: ph-schedule
    lambda_desc: 刘处流处理调度与postgresql数据交互
    lambda_timeout: 30
    lambda_memory_size: 128
    vpc_config:
      SubnetIds:
      - 'subnet-0260eab5acd58bc53'
      - 'subnet-0e3daa88acef9b136'
      SecurityGroupIds:
      - 'sg-058404c2ad02dcbb9'
      - 'sg-09f5205a1194149ab'
    lambda_env:
      TEST: test
    lambda_tag:
      language: nodejs10.x
  gateway:
    rest_api_id: 2t69b7x032
    api_template: s3://ph-platform/2020-08-10/template/python/phcli/lmd/jsonapi-openapi-template.yaml
    lambda_name: ph-schedule
    alias_version: current
