version: 0.2
phases:
  install: 
    runtime-versions:
      nodejs: 14
  build:
    commands:
      - cp /environment/node/code/web_node_modules.tar .
      - ls
      - cd micro-frontend
      - ls
      - cd bpcatelogpage
      - cp ../../web_node_modules.tar .
      - tar -xf web_node_modules.tar
      - mv web_node_modules node_modules
      - ls
      - ember build --environment production
      - cp ../../README.md ./dist
      - rm -rf node_modules
      - rm web_node_modules.tar
      - ls
      - cd ..
      - cd max
      - cp ../../web_node_modules.tar .
      - tar -xf web_node_modules.tar
      - mv web_node_modules node_modules
      - ember build --environment production
      - cp ../../README.md ./dist
      - rm -rf node_modules
      - rm web_node_modules.tar
      - ls
      - cd ..
      - cd pharbers-web
      - cp ../../web_node_modules.tar .
      - tar -xf web_node_modules.tar
      - mv web_node_modules node_modules
      - ember build --environment production
      - cp ../../README.md ./dist
      - rm -rf node_modules
      - rm web_node_modules.tar
      - ls
      - cd ..
      - cd vue-web-components
      - cd vue-basic-component
      - cp ../../../web_node_modules.tar .
      - tar -xf web_node_modules.tar
      - mv web_node_modules node_modules
      - npm run build:component
      - yarn link
      - cp ../../../README.md ./dist
      - ls
      - mv web_node_modules.tar ../vue-excel-component/
      - cd ..
      - cd vue-excel-component
      - tar -xf web_node_modules.tar
      - mv web_node_modules node_modules
      - yarn link "vue-components"
      - npm run build:component
      - mv web_node_modules.tar ../vue-catelog-component/
      - cp ../../../README.md ./dist
      - ls
      - cd ..
      - cd vue-catelog-component
      - tar -xf web_node_modules.tar
      - mv web_node_modules node_modules
      - yarn link "vue-components"
      - npm run build:component
      - mv web_node_modules.tar ../vue-dag-component/
      - cp ../../../README.md ./dist
      - cd ..
      - cd vue-dag-component
      - tar -xf web_node_modules.tar
      - mv web_node_modules node_modules
      - yarn link "vue-components"
      - npm run build:component
      - ls
      - mv web_node_modules.tar ../vue-echarts-component/
      - cp ../../../README.md ./dist
      - cd ..
      - cd vue-echarts-component
      - tar -xf web_node_modules.tar
      - mv web_node_modules node_modules
      - yarn link "vue-components"
      - npm run build:component
      - ls
      - cp ../../../README.md ./dist
      - rm web_node_modules.tar
      - cd ..
      - rm -rf vue-basic-component/node_modules
      - rm -rf vue-catelog-component/node_modules
      - rm -rf vue-dag-component/node_modules
      - rm -rf vue-echarts-component/node_modules
      - rm -rf vue-excel-component/node_modules

artifacts:
  files:
    - micro-frontend/**/*
  type: zip
  name: offweb-$(date +%Y-%m-%d-%HH-%mm-%ss)-V0.0.1.zip
  s3-prefix: 2020-11-11/cicd/offweb/artifacts
#
#reports:
#  arn:aws-cn:codebuild:cn-northwest-1:444603803904:report-group/phlambda-project-phlambda-report-group:
#    files:
#      - $PROJECT_NAME-report-file.xml
#    base-directory: $PROJECT_NAME-report-directory
#    file-format: JUNITXML
