version: 0.2
phases:
  install: 
    runtime-versions:
      nodejs: 14
  build:
    commands:
      - cd phlambda
      - cd phauthentication
      - mkdir lmdcode
      - ln -s /environment/node/code/node_modules node_modules
      - npm run build
      - cp -r dist lmdcode
      - cp ../../README.md lmdcode
      - cp app.js lmdcode
      - curl https://ph-platform.s3.cn-northwest-1.amazonaws.com.cn/2020-11-11/cicd/template/samdeploylmd.sh -o samdeploylmd.sh
      - sed -i s/PROJECT_NAME/phauthentication/  ./samdeploylmd.sh
      - sh samdeploylmd.sh
      - cd ..
      - cd phoauth
      - ln -s /environment/node/code/node_modules node_modules
      - mkdir lmdcode
      - npm run build
      - cp -r dist lmdcode
      - cp ../../README.md lmdcode
      - cp app.js lmdcode
      - ls lmdcode
      - curl https://ph-platform.s3.cn-northwest-1.amazonaws.com.cn/2020-11-11/cicd/template/samdeploylmd.sh -o samdeploylmd.sh
      - sed -i s/PROJECT_NAME/phoauth/  ./samdeploylmd.sh
      - sh samdeploylmd.sh
      - cd ..
      - cd phstepfunctionindex
      - ln -s /environment/node/code/node_modules node_modules
      - mkdir lmdcode
      - npm run build
      - cp -r dist lmdcode
      - cp app.js lmdcode
      - cp ../../README.md lmdcode
      - curl https://ph-platform.s3.cn-northwest-1.amazonaws.com.cn/2020-11-11/cicd/template/samdeploylmd.sh -o samdeploylmd.sh
      - sed -i s/PROJECT_NAME/phstepfunctionindex/  ./samdeploylmd.sh
      - sh samdeploylmd.sh
      - cd ..
      - cd phuseragent
      - mkdir lmdcode
      - cp -r config lmdcode
      - cp -r dist_1 lmdcode/dist
      - cp app.js lmdcode
      - cp ../../README.md lmdcode
      - ls lmdcode
      - curl https://ph-platform.s3.cn-northwest-1.amazonaws.com.cn/2020-11-11/cicd/template/samdeploylmd.sh -o samdeploylmd.sh
      - sed -i s/PROJECT_NAME/phuseragent/  ./samdeploylmd.sh
      - sh samdeploylmd.sh
      - cd ..
      - cd phplatform
      - ln -s /environment/node/code/node_modules node_modules
      - mkdir lmdcode
      - npm run build
      - cp -r dist lmdcode
      - cp app.js lmdcode
      - cp ../../README.md lmdcode
      - curl https://ph-platform.s3.cn-northwest-1.amazonaws.com.cn/2020-11-11/cicd/template/samdeploylmd.sh -o samdeploylmd.sh
      - sed -i s/PROJECT_NAME/phplatform/  ./samdeploylmd.sh
      - sh samdeploylmd.sh
      - cd ..
      - cd phcreateproject
      - ln -s /environment/node/code/node_modules node_modules
      - mkdir lmdcode
      - npm run build
      - cp -r dist lmdcode
      - cp app.js lmdcode
      - cp ../../README.md lmdcode
      - curl https://ph-platform.s3.cn-northwest-1.amazonaws.com.cn/2020-11-11/cicd/template/samdeploylmd.sh -o samdeploylmd.sh
      - sed -i s/PROJECT_NAME/phplatform/  ./samdeploylmd.sh
      - sh samdeploylmd.sh
      - cd ..
artifacts:
  files:
    - phlambda/**/**
  type: zip
  name: $PROJECT_NAME-$(date +%Y-%m-%d)
  s3-prefix: 2020-11-11/cicd/$PROJECT_NAME/artifacts

#reports:
#  arn:aws-cn:codebuild:cn-northwest-1:444603803904:report-group/phlambda-project-phlambda-report-group:
#    files:
#      - phplatform-report-file.xml
#    base-directory: phplatform-report-directory
#    file-format: JUNITXML
