version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - cd phlambda
      - python3 -m pytest --junitxml=reportfile/python3report-file.xml
      - cd ..

  build:
    commands:
      - cd phlambda
      - cd phchupdatesql
      - cp ../../README.md src/
      - curl https://ph-platform.s3.cn-northwest-1.amazonaws.com.cn/2020-11-11/cicd/template/samdeploylmd.sh -o samdeploylmd.sh
      - sed -i s/PROJECT_NAME/phchupdatesql/  ./samdeploylmd.sh
      - sh samdeploylmd.sh
      - cd ..
      - cd phchdatasource
      - cp ../../README.md src/
      - curl https://ph-platform.s3.cn-northwest-1.amazonaws.com.cn/2020-11-11/cicd/template/samdeploylmd.sh -o samdeploylmd.sh
      - sed -i s/PROJECT_NAME/phchdatasource/  ./samdeploylmd.sh
      - sh samdeploylmd.sh
      - cd ..
      - cd phnoticesms
      - cp ../../README.md src/
      - curl https://ph-platform.s3.cn-northwest-1.amazonaws.com.cn/2020-11-11/cicd/template/samdeploylmd.sh -o samdeploylmd.sh
      - sed -i s/PROJECT_NAME/phnoticesms/  ./samdeploylmd.sh
      - sh samdeploylmd.sh
      - cd ..
      - cd phcicd
      - cp ../../README.md src/
      - curl https://ph-platform.s3.cn-northwest-1.amazonaws.com.cn/2020-11-11/cicd/template/samdeploylmd.sh -o samdeploylmd.sh
      - sed -i s/PROJECT_NAME/phcicd/  ./samdeploylmd.sh
      - sh samdeploylmd.sh
      - cd ..
      - cd phclickhousesql
      - cp ../../README.md src/
      - curl https://ph-platform.s3.cn-northwest-1.amazonaws.com.cn/2020-11-11/cicd/template/samdeploylmd.sh -o samdeploylmd.sh
      - sed -i s/PROJECT_NAME/phclickhousesql/  ./samdeploylmd.sh
      - sh samdeploylmd.sh
      - cd ..
      - cd phcreatestepargs
      - cp ../../README.md src/
      - curl https://ph-platform.s3.cn-northwest-1.amazonaws.com.cn/2020-11-11/cicd/template/samdeploylmd.sh -o samdeploylmd.sh
      - sed -i s/PROJECT_NAME/phcreatestepargs/  ./samdeploylmd.sh
      - sh samdeploylmd.sh
      - cd ..
      - cd phdagrunid
      - cp ../../README.md src/
      - curl https://ph-platform.s3.cn-northwest-1.amazonaws.com.cn/2020-11-11/cicd/template/samdeploylmd.sh -o samdeploylmd.sh
      - sed -i s/PROJECT_NAME/phdagrunid/  ./samdeploylmd.sh
      - sh samdeploylmd.sh
      - cd ..
      - cd phetlsfn
      - cp ../../README.md src/
      - curl https://ph-platform.s3.cn-northwest-1.amazonaws.com.cn/2020-11-11/cicd/template/samdeploylmd.sh -o samdeploylmd.sh
      - sed -i s/PROJECT_NAME/phetlsfn/  ./samdeploylmd.sh
      - sh samdeploylmd.sh
      - cd ..
      - cd phetlstepargs
      - cp ../../README.md src/
      - curl https://ph-platform.s3.cn-northwest-1.amazonaws.com.cn/2020-11-11/cicd/template/samdeploylmd.sh -o samdeploylmd.sh
      - sed -i s/PROJECT_NAME/phetlstepargs/  ./samdeploylmd.sh
      - sh samdeploylmd.sh
      - cd ..
      - cd phgetsfn
      - cp ../../README.md src/
      - curl https://ph-platform.s3.cn-northwest-1.amazonaws.com.cn/2020-11-11/cicd/template/samdeploylmd.sh -o samdeploylmd.sh
      - sed -i s/PROJECT_NAME/phgetsfn/  ./samdeploylmd.sh
      - sh samdeploylmd.sh
      - cd ..
      - cd phgluejob
      - cp ../../README.md src/
      - curl https://ph-platform.s3.cn-northwest-1.amazonaws.com.cn/2020-11-11/cicd/template/samdeploylmd.sh -o samdeploylmd.sh
      - sed -i s/PROJECT_NAME/phgluejob/  ./samdeploylmd.sh
      - sh samdeploylmd.sh
      - cd ..
      - cd phnoticeemail
      - cp ../../README.md src/
      - curl https://ph-platform.s3.cn-northwest-1.amazonaws.com.cn/2020-11-11/cicd/template/samdeploylmd.sh -o samdeploylmd.sh
      - sed -i s/PROJECT_NAME/phnoticeemail/  ./samdeploylmd.sh
      - sh samdeploylmd.sh
      - cd ..
      - cd phnoticeglue
      - cp ../../README.md src/
      - curl https://ph-platform.s3.cn-northwest-1.amazonaws.com.cn/2020-11-11/cicd/template/samdeploylmd.sh -o samdeploylmd.sh
      - sed -i s/PROJECT_NAME/phnoticeglue/  ./samdeploylmd.sh
      - sh samdeploylmd.sh
      - cd ..
      - cd phnoticeiot
      - cp ../../README.md src/
      - curl https://ph-platform.s3.cn-northwest-1.amazonaws.com.cn/2020-11-11/cicd/template/samdeploylmd.sh -o samdeploylmd.sh
      - sed -i s/PROJECT_NAME/phnoticeiot/  ./samdeploylmd.sh
      - sh samdeploylmd.sh
      - cd ..
      - cd phrollback
      - cp ../../README.md src/
      - curl https://ph-platform.s3.cn-northwest-1.amazonaws.com.cn/2020-11-11/cicd/template/samdeploylmd.sh -o samdeploylmd.sh
      - sed -i s/PROJECT_NAME/phrollback/  ./samdeploylmd.sh
      - sh samdeploylmd.sh
      - cd ..
      - cd phschemaexplorer
      - cp ../../README.md src/
      - curl https://ph-platform.s3.cn-northwest-1.amazonaws.com.cn/2020-11-11/cicd/template/samdeploylmd.sh -o samdeploylmd.sh
      - sed -i s/PROJECT_NAME/phschemaexplorer/  ./samdeploylmd.sh
      - sh samdeploylmd.sh
      - cd ..
      - cd phstartcrawler
      - cp ../../README.md src/
      - curl https://ph-platform.s3.cn-northwest-1.amazonaws.com.cn/2020-11-11/cicd/template/samdeploylmd.sh -o samdeploylmd.sh
      - sed -i s/PROJECT_NAME/phstartcrawler/  ./samdeploylmd.sh
      - sh samdeploylmd.sh
      - cd ..
      - cd phtmppsycopg
      - cp ../../README.md src/
      - curl https://ph-platform.s3.cn-northwest-1.amazonaws.com.cn/2020-11-11/cicd/template/samdeploylmd.sh -o samdeploylmd.sh
      - sed -i s/PROJECT_NAME/phtmppsycopg/  ./samdeploylmd.sh
      - sh samdeploylmd.sh
      - cd ..
      - cd phworkflow
      - cp ../../README.md src/
      - curl https://ph-platform.s3.cn-northwest-1.amazonaws.com.cn/2020-11-11/cicd/template/samdeploylmd.sh -o samdeploylmd.sh
      - sed -i s/PROJECT_NAME/phworkflow/  ./samdeploylmd.sh
      - sh samdeploylmd.sh
      - cd ..
      - cd phxlsxtockhouse
      - cp ../../README.md src/
      - curl https://ph-platform.s3.cn-northwest-1.amazonaws.com.cn/2020-11-11/cicd/template/samdeploylmd.sh -o samdeploylmd.sh
      - sed -i s/PROJECT_NAME/phxlsxtockhouse/  ./samdeploylmd.sh
      - sh samdeploylmd.sh
      - cd ..
      - cd phdagcicd
      - cp ../../README.md src/
      - curl https://ph-platform.s3.cn-northwest-1.amazonaws.com.cn/2020-11-11/cicd/template/samdeploylmd.sh -o samdeploylmd.sh
      - sed -i s/PROJECT_NAME/phdagcicd/  ./samdeploylmd.sh
      - sh samdeploylmd.sh
      - cd ..
      - cd phdydatasource
      - cp ../../README.md src/
      - curl https://ph-platform.s3.cn-northwest-1.amazonaws.com.cn/2020-11-11/cicd/template/samdeploylmd.sh -o samdeploylmd.sh
      - sed -i s/PROJECT_NAME/phdydatasource/  ./samdeploylmd.sh
      - sh samdeploylmd.sh
      - cd ..
artifacts:
  files:
    - phlambda/**/**
  type: zip
  name: $PROJECT_NAME-$(date +%Y-%m-%d)
  s3-prefix: 2020-11-11/cicd/$PROJECT_NAME/artifacts

reports:
  arn:aws-cn:codebuild:cn-northwest-1:444603803904:report-group/phlambda-project-phlambda-report-group:
    files:
      - python3report-file.xml
    base-directory: phlambda/reportfile
    file-format: JUNITXML
