AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: cicd lambda
Resources:
  ATTFFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.8
      AutoPublishAlias: Current
      CodeUri: ./src
      Layers:
        - arn:aws-cn:lambda:cn-northwest-1:444603803904:layer:PhMetricLayer:1
      Environment:
        Variables:
          ARN: arn:aws-cn:states:cn-northwest-1:444603803904:stateMachine:scenario-deletion
          EDITION: "DEV"
      FunctionName: lmd-phscenariosdeletiontrigger-dev
      Description: Http Post接口触发StepFunctions 删除 sceanrio（scenarios)
      Role: arn:aws-cn:iam::444603803904:role/Ph-Data-Resource-Admin
      MemorySize: 1024
      Timeout: 600
