AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: cicd lambda
Resources:
  ATTFFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.8
      AutoPublishAlias: Current
      CodeUri: s3://ph-platform/2020-11-11/cicd/phversion/samtem/7361aef5e0d61ef49f71e73a80812327
      Environment:
        Variables:
          UPLOAD_PATH: /mnt/tmp/max/tmp/
      Layers:
      - arn:aws-cn:lambda:cn-northwest-1:444603803904:layer:phdydatasource:1
      FunctionName: lmd-phversion-dev
      MemorySize: 512
      Description: phversion-v2
      Role: arn:aws-cn:iam::444603803904:role/Ph-Back-RW
      Timeout: 60
