AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: cicd lambda
Resources:
  ATTFFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.8
      AutoPublishAlias: Current
      CodeUri: ./src
      FileSystemConfigs:
        - Arn: arn:aws-cn:elasticfilesystem:cn-northwest-1:444603803904:access-point/fsap-03c2a9f1b9fcf6942
          LocalMountPath: /mnt/tmp
      Environment:
        Variables:
          UPLOAD_PATH: "/mnt/tmp/max/tmp/"
          EDITION: "DEV"
      Layers:
        - arn:aws-cn:lambda:cn-northwest-1:444603803904:layer:phdydatasource:1
      FunctionName: phversion
      MemorySize: 512
      Description: "phversion-v2"
      Role: arn:aws-cn:iam::444603803904:role/Ph-Back-RW
      Timeout: 60
      Events:
        Type: DynamoDB
        Properties:
          Stream: arn:aws-cn:dynamodb:cn-northwest-1:444603803904:table/project_files
          StartingPosition: TRIM_HORIZON
          BatchSize: 1
          Enabled: No
