AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: cicd offweb
Resources:
  ATTFFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.8
      AutoPublishAlias: Current
      CodeUri: s3://ph-platform/2020-11-11/offweb/samtem/76c28c79ea27c21213edac15b955e666
      Environment:
        Variables:
          GIT_URL: https://hbzhao:123456@bitbucket.pharbers.com/scm/fron/micro-frontend.git
          README_S3_PATH: 2020-11-11/cicd/template/codebuild/README.md
          README_FILE_PATH: /tmp/README.md
          BUILDSEPC_S3_PATH: 2020-11-11/cicd/template/codebuild/frontendbuildspec.yaml
          BUILDSEPC_FILE_PATH: /tmp/frontendbuildspec.yaml
      Layers:
      - arn:aws-cn:lambda:cn-northwest-1:444603803904:layer:PhCICD:3
      - arn:aws-cn:lambda:cn-northwest-1:444603803904:layer:lambda-git:3
      FunctionName: lmd-phfrontendcicd-V2
      MemorySize: 1024
      Description: "\u524D\u7AEF\u7684cicd\u6D41\u7A0B"
      Role: arn:aws-cn:iam::444603803904:role/Ph-Data-Resource-Admin
      Timeout: 600
