AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: cicd lambda phresetpwd-v2
Resources:
  ATTFFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambdaHandler
      Runtime: python3.8
      CodeUri: ./src
      Layers:
        - arn:aws-cn:lambda:cn-northwest-1:444603803904:layer:psycopg2:4
      FunctionName: phresetpwd
      Description: "通过邮件地址修改密码"
      MemorySize: 512
      Role: arn:aws-cn:iam::444603803904:role/Ph-Cli-Lmd
      Timeout: 30
      Environment:
        Variables:
          DBNAME: "phplatform"
          USER: "pharbers"
          PASSWORD: "Abcde196125"
          HOST: "192.168.74.58"
          PORT: "5439"
          EDITION: "DEV"
      VpcConfig:
        SecurityGroupIds:
          - sg-058404c2ad02dcbb9
          - sg-09f5205a1194149ab
        SubnetIds:
          - subnet-0260eab5acd58bc53
          - subnet-0e3daa88acef9b136
