AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: cicd lambda
Resources:
  ATTFFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.8
      CodeUri: ./src
      Environment:
        Variables:
          EDITION: "DEV"
#      Layers:
#        - arn:aws-cn:lambda:cn-northwest-1:444603803904:layer:phdydatasource:1
      FunctionName: phnotification
      MemorySize: 1024
      Description: "HTTP形式的状态查询接口"
      Role: arn:aws-cn:iam::444603803904:role/Ph-Back-RW
      Timeout: 600

