AWSTemplateFormatVersion: 2010-09-09
Description: lambda codebuild cloudformation
Parameters:
  VPCIdentifier:
    Type: String
    Default: vpc-082167a9cbf8811e1
    Description : "VPC ID"
  PublicSubnetIdentifier:
    Type: String
    Default: subnet-0260eab5acd58bc53
    Description : "public subnet one"
  PrivateSubnetIdentifier:
    Type: String
    Default: subnet-0eb162dcc3b5a3a43
    Description : "private subnet with nat gateway"
  SecurityGroupIdentifier:
    Type: String
    Default: sg-09f5205a1194149ab
    Description : "security group"
  Concurrency:
    Type: Number
    Default: 1
    Description : "Concurrent build limit"
  TimeoutInMinutes:
    Type: Number
    Default: 480
    Description : "TimeoutInMinutes"
  BuildSpec:
    Type: String
    Default: vueFrontBuildspec
    Description: "BuildSpec"
  GitCommit:
    Type: String
    Default: 442ce2ff73d653913ea964c62a5efa1d4e5d15b5
    Description: "GitCommit"
  GitUrl:
    Type: String
    Default: http://cicd:Abcde196125@192.168.53.179:7990/scm/fron/micro-frontend.git
    Description: "GitUrl"
  ComponentName:
    Type: String
    Default: vue-excelv2-component
    Description: "BranchName"
  ComponentPath:
    Type: String
    Default: vue-web-components/vue-excelv2-component
    Description: "BranchName"
  BranchName:
    Type: String
    Default: PBDP-3235-cicd
    Description: "BranchName"
  RepoName:
    Type: String
    Default: micro-frontend
    Description: "RepoName"
  S3ComponentPath:
    Type: String
    Default: s3://ph-platform/2020-11-11/cicd/test/vue-excelv2-component/
    Description: "Version"

Resources:
  PharbersAutoBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref "AWS::StackName"
      ConcurrentBuildLimit: !Ref Concurrency
      Cache:
        Location: NO_CACHE
        Modes:
          - LOCAL_SOURCE_CACHE
          - LOCAL_DOCKER_LAYER_CACHE
          - LOCAL_CUSTOM_CACHE
        Type: NO_CACHE
      Description: Build Web
      Environment:
        ComputeType: BUILD_GENERAL1_MEDIUM
        Image: !Sub 444603803904.dkr.ecr.cn-northwest-1.amazonaws.com.cn/cicd_frontend:latest
        ImagePullCredentialsType: SERVICE_ROLE
        Type: LINUX_CONTAINER
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: COMPONENT_NAME
            Type: PLAINTEXT
            Value: !Ref ComponentName
          - Name: REPO_NAME
            Type: PLAINTEXT
            Value: !Ref RepoName
          - Name: AWS_ACCESS_KEY
            Type: PLAINTEXT
            Value: AKIAWPBDTVEAPOX3QT6U
          - Name: AWS_SECRET_KEY
            Type: PLAINTEXT
            Value: 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
          - Name: BRANCH_NAME
            Type: PLAINTEXT
            Value: !Ref BranchName
          - Name: GIT_COMMIT
            Type: PLAINTEXT
            Value: !Ref GitCommit
          - Name: GIT_URL
            Type: PLAINTEXT
            Value: !Ref GitUrl
          - Name: COMPONENT_PATH
            Type: PLAINTEXT
            Value: !Ref ComponentPath
          - Name: S3_COMPONENT_PATH
            Type: PLAINTEXT
            Value: !Ref S3ComponentPath

#      FileSystemLocations:
#        - Identifier: EFS
#          Location: fs-1dbf2af8.efs.cn-northwest-1.amazonaws.com.cn:/code
#          MountPoint: /code
#          Type: EFS
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
        S3Logs:
          Status: ENABLED
          EncryptionDisabled: true
          Location: !Sub ph-platform/2020-11-11/cicd/frontend/${ComponentPath}/logs
      QueuedTimeoutInMinutes: !Ref TimeoutInMinutes
      ServiceRole: arn:aws-cn:iam::444603803904:role/Pharbers-CICD-Maintainer
      # SourceVersion: 0.0.1 Might be useful late on
      Source:
        BuildSpec: !Sub ${BuildSpec}.yaml
        Location: !Sub ph-platform/2020-11-11/cicd/frontend/${BuildSpec}/code.zip
        Type: S3
      Artifacts:
        ArtifactIdentifier: String
        EncryptionDisabled: true
        Location: ph-platform # this is the name of the output bucket
        NamespaceType: BUILD_ID
        Packaging: ZIP
        Path: !Sub 2020-11-11/cicd/${ComponentPath}/artifacts/
        Type: S3
        OverrideArtifactName: true
      Tags:
        - Key: Company
          Value: Pharbers
        - Key: Project
          Value: !Ref ComponentName
      TimeoutInMinutes: !Ref TimeoutInMinutes
      # Triggers: Might be useful late on
      VpcConfig:
        SecurityGroupIds:
          - !Ref SecurityGroupIdentifier
        Subnets:
          - !Ref PublicSubnetIdentifier
          - !Ref PrivateSubnetIdentifier
        VpcId: !Ref VPCIdentifier

