    Type: 'AWS::ApiGateway::Method'
    Properties:
      ApiKeyRequired: false
      RestApiId: ${RestApiId}
      ResourceId: !Ref ${ReplaceResource}
      RequestParameters:
        method.request.path.proxy: true #加上这组参数可以添加proxy
        method.request.header.Accept: true
        method.request.header.Content-Type: true
      HttpMethod: POST
      AuthorizationType: CUSTOM
      AuthorizerId: ${AuthorizerId}
      Integration:
        Type: "AWS_PROXY"
        Uri: arn:aws-cn:apigateway:cn-northwest-1:lambda:path/2015-03-31/functions/arn:aws-cn:lambda:cn-northwest-1:444603803904:function:${ReplaceLmdName}/invocations
        IntegrationHttpMethod: "POST"
        Credentials: arn:aws-cn:iam::444603803904:role/Ph-Cli-Lmd
        TimeoutInMillis: 29000
        RequestParameters:
          integration.request.path.proxy: 'method.request.path.proxy'
        IntegrationResponses:
          - StatusCode: "200"
      MethodResponses:
        - StatusCode: "200"
          ResponseParameters:
            "method.response.header.Access-Control-Allow-Origin": Fasle
          ResponseModels:
            "application/json": "Empty"
